buildscript {
    repositories {
        maven {
            url 'http://localhost:8080/snapshots'
        }

        mavenCentral()
    }

    dependencies {
        classpath 'info.gianlucacosta.aurora:aurora:10.0.0-SNAPSHOT'
    }
}

plugins {
    id 'java'
    id 'maven'
}

apply plugin: 'info.gianlucacosta.aurora'

group 'info.gianlucacosta.atlas'
archivesBaseName = 'atlas'
version '2.0.0-SNAPSHOT'

description = 'Interactive cartography for Java'

sourceCompatibility = 1.8

dependencies {
    compile 'org.jxmapviewer:jxmapviewer2:2.2'

    compile 'info.gianlucacosta.zephyros:zephyros-core:2.0-SNAPSHOT'
}

aurora {
    gitHubUser = 'giancosta86'

    author {
        name = 'Gianluca Costa'
        email = 'gianluca@gianlucacosta.info'
        url = 'http://gianlucacosta.info/'
    }

    mavenDeploy {
        url = 'http://localhost:8080/snapshots'
    }
}
